gos_web_socket:
  client:
    session_handler:      ~ # Example: @session.handler.pdo
    firewall:             ws_firewall # Example: secured_area
    storage:
      driver:               gos_web_socket.client.driver.in_memory # Example: gos_web_socket.client.driver.in_memory
      ttl:                  900 # Example: 3600
      prefix:               '' # Example: client
      decorator:            ~
  shared_config:        true
  server:
    port: 1337              # ~ # Required, Example: 1337
    host: 0.0.0.0           # ~ # Required, Example: 127.0.0.1
    origin_check: false     # Example: true


    keepalive_ping: true    # Flag indicating a keepalive ping should be enabled on the server
    keepalive_interval: 10  # The time in seconds between each keepalive ping
  #  router:
  #    resources: []
  #origins: []
  #pushers:
    #amqp:
    #  enabled:              false
    #  host:                 ~ # Required, Example: 127.0.0.1
    #  port:                 ~ # Required, Example: 5672
    #  login:                ~ # Required
    #  password:             ~ # Required
    #  vhost:                /
    #  read_timeout:         0
    #  write_timeout:        0
    #  connect_timeout:      0
    #  queue_name:           gos_websocket
    #  exchange_name:        gos_websocket_exchange
